NAME = fdf

# ***** APARIENCE ************************************************************* #

DEL_LINE 			= \033[2K
ITALIC 				= \033[3m
BOLD 				= \033[1m
DEF_COLOR 			= \033[0;39m
GRAY 				= \033[0;90m
RED 				= \033[0;91m
GREEN 				= \033[0;92m
YELLOW 				= \033[0;93m
BLUE 				= \033[0;94m
MAGENTA 			= \033[0;95m
CYAN 				= \033[0;96m
WHITE 				= \033[0;97m
BLACK 				= \033[0;99m
ORANGE 				= \033[38;5;209m
BROWN 				= \033[38;2;184;143;29m
DARK_GRAY 			= \033[38;5;234m
MID_GRAY 			= \033[38;5;245m
DARK_GREEN 			= \033[38;2;75;179;82m
DARK_YELLOW 		= \033[38;5;143m

# ***** COMPILE ************************************************************* #

CC 					= clang
AR 					= ar rcs
RM 					= rm -f
MK 					= make -C
MKD					= mkdir -p
MCL 				= make clean -C
MFCL 				= make fclean -C
MK_					= && make

# ***** DIRECTORIES ************************************************************* #

SRC_DIR				= ./src
CONTROL_DIR			= ./control
DRAW_DIR			= ./draw
ERRORS_DIR			= ./errors
INIT_DIR			= ./init
UTILS_DIR			= ./utils
LIBRARIES			= ./libs
OBJ_DIR				= ./objects
LIBFT_DIR			= libft
PRINTFT_DIR			= printf
GNL_DIR				= gnl
INCLUDES_DIR		= ./includes
MLX42_LIB			= ./MLX42/lib
MLX42_INCLUDE		= ./MLX42/include/MLX42

# ***** LIBRARY .a ************************************************************* #

LIBFT_A				= ${LIBRARIES}/${LIBFT_DIR}/libft.a
PRINTFT_A			= ${LIBRARIES}/${PRINTFT_DIR}/libftprintf.a
LIBMLX42_A			= ${MLX42_LIB}/libmlx42.a

